In [1]:
import pandas as pd
import numpy as np

import ghostPii as gp

/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "

In [2]:
surveyResults = pd.read_csv('demo_data/medical_survey.csv')
surveyResults

,Name,Phone,Aches,Cough,Fatigue,Sore Throat,Runny Nose,Temperature
0,Griffin Guzman,1-313-262-6944,0,0,1,0,0,102.5
1,Gray Burks,1-627-483-8969,1,0,0,0,0,102.2
2,Burke Gibbs,1-899-772-9407,1,0,0,0,0,97.1
3,Hilel Sheppard,1-957-866-7333,0,0,1,1,0,101.1
4,Jasper Slater,1-691-353-4183,0,0,1,0,0,101.9
...,...,...,...,...,...,...,...,...
295,Minerva Sykes,1-143-977-2591,0,1,1,1,0,98.9
296,Scott Glenn,1-325-987-3047,0,0,0,1,0,99.8
297,Whoopi Mejia,1-732-950-5226,0,0,1,1,0,97.7
298,Charity Brennan,1-383-654-0965,0,0,0,0,0,103.1
299,Reed Wells,1-760-150-1927,1,0,1,0,0,100.2

In [3]:
# encrypt the data using doctor's token
headers = {'Authorization': 'Token 50086974f7e8fa7dd2688300b0fe41d25ea76eaa'}
doctorContext = gp.CryptoContext(headers)

encryptedResults = gp.NormCipherFrame(doctorContext,surveyResults,keyRange=500)
encryptedResults[0:7].frame_of_ciphertext()

,0,1,2,3,4,5,6
0,"L#!E'!R""!q(!m""!>#!E#!,%!7""!B'!H%!X(!&&!!'!&#!l...","o%!U""!?#!%(!9#!c'!1%!M%!D#!P&!1""!p#!P'!#""!",^'!,%&!,<!!,1'!,u!!
1,"K&!V#!X(!J'!q#!5(!@(!T""!m#!4#!L""!S#!M!!'&!#&!-...","B&!M'!=""!>&!W""!N""!2""!q""!z#!2""!c&!H'!s%!*'!",3'!,(!!,"T""!","s""!",*'!
2,"K""!1'!<'!(&!9""!K%!X%!a#!""'!c'!'&!j#!T""!Q!!j!!R...",u!!O#!a%!0'!7&!%&!K'!y&!1(!c#!i'!p'!J'!k'!,"8""!",k!!,!%!,(&!,=%!
3,"A'!u&!8&!T&!)&!V#!g""!%'!P&!u#!F(!#&!:#!:'!l""!O...","2(!F%!R&!U""!W""!X""!l""!O'!y%!w""!;%!<&!`""!n%!",.#!,z#!,h!!,"h""!",2!!
4,"n#!T&!s%!+&!V%!['!M!!k&!l""!H#!b#!!&!W&!J""!g#!6...",".%!A'!U%!q'!h%!M'!*'!q&!9%!A""!l'!U%!_&!j'!",a&!,U#!,^&!,-%!,C#!
...,...,...,...,...,...,...,...
295,"i""!<""!s%!e'!F%!Q#!b&!.&!8&!T&!b%!n(!`%!8""!t%!....","h""!-'!)%!Z#!h#!F'!I%!B""!H'!g""!#%!P#!u#!F%!",9%!,%&!,J&!,1!!,d%!
296,"Z%!=(!g#!D(!N#!Y'!@'!h""!j""!b""!k(!]&!E'!.%!6&!N...","z!!Z!!r""!i#!n#!k!!E(!_&!4%!1#!-&!Z!!Y%!H'!",1#!,"""&!",0'!,&'!,"q""!"
297,"c%!m%!N'!U#!T&!v&!_&!j""!8%!c'!)%!q%!C%!3""!3#!g...","n#!m%!?'!U'!M#!,&!b&!2%!:&!]#!]&!H&!D'!5#!","7""!",7'!,2#!,S'!,?!!
298,"3&!<#!U""!5%!,#!)#!t%!L#!<(!2(!U""!5&!L%!Z#!O'!7...","k&!['!#'!w#!E&!;""!t'!Y!!=""!o""!m#!q#!!#!r&!",-'!,W&!,c'!,#%!,"F""!"
299,"?&!V'!&(!M""!Y%!<""!n'!Q""!x#!f&!i""!D%!*'!@#!p%!=...","K&!P&!<(!b&!T'!.'!w!!U&!7&!S""!h""!O&!C#!W""!",;!!,o!!,"y""!",1&!,@!!

In [4]:
# now we switch over to the data analyst's token

headers = {'Authorization': 'Token e1cb3d947e61759f1340295d4402a2392f1bf629'}
analystContext = gp.CryptoContext(headers)

encryptedResults.apiContext = analystContext

In [5]:
# now lets add a new column to represent whether or not the temperature is high enough for a fever
hasFever = encryptedResults[7] > 100.5
encHasFever = gp.NormCipherQuant(analystContext,hasFever,fromPlain=True)
encryptedResults = encryptedResults.horiz_merge(encHasFever)

In [6]:
encryptedResults[8].ciphertext()[0:10]

['S&!', 'N.!', '32!', '01!', "?'!", '9.!', '(!!', 'z+!', 'z)!', 'x+!']

In [7]:
# Now let's set up our formula for significance of symptoms
coefficientDict = {'Aches':3,'Cough':2,'Fatigue':4,'Sore Throat':2,'Runny Nose':3,'Fever':7}
formulaStr = "({Aches} * A)+({Cough} * C)+({Fatigue} * Fa)+({SoreThroat} * St)+({RunnyNose} * Rn)+({Fever}* Fe)".format(
    Aches=coefficientDict['Aches'],
    Cough=coefficientDict['Cough'],
    Fatigue=coefficientDict['Fatigue'],
    SoreThroat=coefficientDict['Sore Throat'],
    RunnyNose=coefficientDict['Runny Nose'],
    Fever=coefficientDict['Fever'],
)
variables = ['A','C','Fa','St','Rn','Fe']
formulaStr

'(3 * A)+(2 * C)+(4 * Fa)+(2 * St)+(3 * Rn)+(7* Fe)'

In [8]:
cipherLists = [[encryptedResults.cipherListOfListOfList[colIndex][i][0] for colIndex in [2,3,4,5,6,8]] for i in range(encryptedResults.rows)]
indexLists = [[encryptedResults.indicesListOfListOfList[colIndex][i][0] for colIndex in [2,3,4,5,6,8]] for i in range(encryptedResults.rows)]

diagnosisScore = gp.full_polynomial_compute(analystContext,formulaStr,variables,indexLists,cipherLists,isFloat=False,)

In [9]:
# Now we can add the diagnosis score as a new column on the encrypted data
encryptedResults = encryptedResults.horiz_merge(diagnosisScore)

In [10]:
# We can now split the data to get a data frame of only people whose score is above a threshold
isDiagnosed = diagnosisScore > 15
diagnosedPeople = encryptedResults.vert_slice([index for index in range(encryptedResults.rows) if isDiagnosed[index]==1])
diagnosedPeople.rows

7

In [11]:
# As you can see we can still not access the personal info
diagnosedPeople.decrypt()

json failure

None

TypeError: 'NoneType' object is not iterable

In [12]:
# But we can hand it back over to the doctor for a followup
diagnosedPeople.apiContext = doctorContext
pd.DataFrame(diagnosedPeople.decrypt()).transpose().rename({0:'Name',1:'Phone Number',2:'Aches',3:'Cough',4:'Fatigue',5:'Sore Throat',6:'Runny Nose',7:'Temperature',8:'Has Fever',9:'Score'},axis=1)

,Name,Phone Number,Aches,Cough,Fatigue,Sore Throat,Runny Nose,Temperature,Has Fever,Score
0,Lucian Beard,1-743-602-6764,1,1,1,0,1,103.1,1,19
1,Cameron Morrison,1-833-374-6688,1,0,1,0,1,102.6,1,17
2,Tamara Montoya,1-902-191-4844,1,0,1,1,0,101.1,1,16
3,Griffin Styles,1-752-119-3104,1,1,1,1,0,101.3,1,18
4,Tashya Rodgers,1-500-996-2192,1,0,1,1,0,100.8,1,16
5,Blake Barber,1-164-344-4665,0,1,1,0,1,101.5,1,16
6,Unity Hogan,1-718-208-4018,1,1,0,1,1,103.3,1,17